---
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - cpanm --with-recommends --installdeps -n .
language: perl
matrix:
  include:
    - perl: '5.22'
    - perl: '5.24'
    - perl: '5.26'
    - perl: '5.28'
    - perl: '5.30'
script:
  - prove -l t
